package PWM

import chisel3._
import chisel3.util._
import chisel3.iotesters.{ChiselFlatSpec, SteppedHWIOTester}

class PWMTest extends SteppedHWIOTester{   
  
  val device_under_test = Module( new PWM(4) )
  val c = device_under_test
  enable_all_debug = true

  for(i <- 0 until 3){
    
    var rise = rnd.nextInt((1 << c.w) - 1) + 1
    var fall = rnd.nextInt((1 << c.w) - 1) + 1  

    println(rise + "," + fall)
    
    poke(c.io.rise, rise)
    poke(c.io.fall, fall) 
    
    for(j <- 0 until (if(i == 0) rise else (rise-1))){
      step(1)
      expect(c.io.out, 1)
    }

    for(k <- 0 until fall){  
      step(1)
      expect(c.io.out, 0)
    } 

    step(1)
    expect(c.io.out, 1)
  }
}

class PWMATPTester extends ChiselFlatSpec {
  "PWM" should "compile and run without incident" in {
    assertTesterPasses(new PWMTest)
  }
  // VCD is generated by default and can be found in test_run_dir/MemoryTests/<test_name>/dump.vcd
}
